name: Installing Python

on: [push]

# jobs:
#   build:
#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#           #- macos-12
#           #- windows-latest
#         py-version:
#           - 3.7
#           - 3.8
#           - 3.9
#         # exclude: #added
#         # - os: macos-12 #added
#         #   py-version: 3.9 #added
#     runs-on: '${{ matrix.os }}'
#     steps:
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '${{ matrix.py-version }}'
        
#     - uses: actions/checkout@v4.1.1

#     - run: |
#         issue_title="${{ github.event.issue.title }}"
#         if [[ "$issue_title" == *"bug"* ]]; then
#           echo "Issue is about a bug!"
#         else
#           echo "Issue is not about a bug"
#         fi

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
        
